---
appveyor.yml:
  delete: true

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  branches:
    - release 

Gemfile:
  required:
    ':system_tests':
      - gem: beaker
        version: '~> 3.13'
        from_env: BEAKER_VERSION
