---
appveyor.yml:
  delete: true

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  branches:
    - release 

Gemfile:
  required:
    ':system_tests':
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: nokogiri
